show_downloads: false
description: A Coding Blog
title: Nick Wilcox
theme: jekyll-theme-minimal
google_analytics: UA-166850209-1
author:
    name: "Nick Wilcox"
    links:
      - label: "Twitter"
        icon: "fab fa-fw fa-twitter-square"
        url: "https://twitter.com/redbluemonkey"
      - label: "GitHub"
        icon: "fab fa-fw fa-github"
        url: "https://github.com/nickwilcox"